### ISSUE TITLE
Make the game playable

### ISSUE THREAD

**Issue by Taneb** [sirpent-team/sirpent-rust#2]
- Errored out player snakes should repeat previous move
- Each tick, all snakes advance by their move
- A snake which turns out to be dead in the _new_ state dies. Its head is removed, and all other segments turn to food.
- Each turn, have n(life snakes)-1 pieces of food.
- Spawn snakes as just the head

**Comment by 46bit** [comment]
Sirpent-rust now essentially works, albeit with many defects to be addressed. Here's an update on these bullet points:
- Errored-out player snakes die immediately, being replaced with food before anything can collide with them.
- Each tick, all snakes advance by their move.
- A snake which turns out to be dead in the new state dies. All segments turn to food.
  - "_Its head is removed_" might still be helpful for having logically simple rules.
- The only food available comes from dead snakes. Food is never removed even when eaten - obviously a bug.
- Spawn snakes as just the head.

I'll try to fill out all defects I can think of as issues to start tidying up!

**Comment by 46bit** [comment]
I believe `sirpent-rust` nearly works! However it needs a few things:

* [x] Player management. When Snakes die, players need evicting (or at least ignoring).
* [x] Players should be told `CauseOfDeath`. I'm rather happy to bring this `sirpent-go` concept back so neatly in https://github.com/sirpent-team/sirpent-rust/commit/15299159a4ceda855c46532b205377f7ce89f906.

**Comment by 46bit** [comment]
I believe this is now playable! 😄 Albeit with much refactoring needed.
